config/routes.rb
Rails.application.routes.draw do
  resources :presences
  resources :students
  resources :lessons
  resources :teachers
  resources :professors
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/presence.rb
class Presence < ApplicationRecord
  belongs_to :student
  belongs_to :lesson

  enum situation: {
    Presente:0,
    Ausente: 1
  }
end

app/controllers/presences_controller.rb
class PresencesController < ApplicationController
  before_action :set_presence, only: [:show, :edit, :update, :destroy]

  # GET /presences
  # GET /presences.json
  def index
    @presences = Presence.all
  end

  # GET /presences/1
  # GET /presences/1.json
  def show
  end

  # GET /presences/new
  def new
    @presence = Presence.new
  end

  # GET /presences/1/edit
  def edit
  end

  # POST /presences
  # POST /presences.json
  def create
    @presence = Presence.new(presence_params)

    respond_to do |format|
      if @presence.save
        format.html { redirect_to @presence, notice: 'Presence was successfully created.' }
        format.json { render :show, status: :created, location: @presence }
      else
        format.html { render :new }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presences/1
  # PATCH/PUT /presences/1.json
  def update
    respond_to do |format|
      if @presence.update(presence_params)
        format.html { redirect_to @presence, notice: 'Presence was successfully updated.' }
        format.json { render :show, status: :ok, location: @presence }
      else
        format.html { render :edit }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presences/1
  # DELETE /presences/1.json
  def destroy
    @presence.destroy
    respond_to do |format|
      format.html { redirect_to presences_url, notice: 'Presence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presence
      @presence = Presence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presence_params
      params.require(:presence).permit(:situation, :student_id, :lesson_id)
    end
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/views/presences/_form.html.erb
<%= form_with(model: presence, local: true) do |form| %>
  <% if presence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(presence.errors.count, "error") %> prohibited this presence from being saved:</h2>

      <ul>
        <% presence.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :situation %>
    <%= form.number_field :situation %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id %>
  </div>

  <div class="field">
    <%= form.label :lesson_id %>
    <%= form.text_field :lesson_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/presences/edit.html.erb
<h1>Editing Presence</h1>

<%= render 'form', presence: @presence %>

<%= link_to 'Show', @presence %> |
<%= link_to 'Back', presences_path %>

app/views/presences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Presences</h1>

<table>
  <thead>
    <tr>
      <th>Situation</th>
      <th>Student</th>
      <th>Lesson</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presences.each do |presence| %>
      <tr>
        <td><%= presence.situation %></td>
        <td><%= presence.student_id %></td>
        <td><%= presence.lesson_id %></td>
        <td><%= link_to 'Show', presence %></td>
        <td><%= link_to 'Edit', edit_presence_path(presence) %></td>
        <td><%= link_to 'Destroy', presence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Presence', new_presence_path %>

app/views/presences/new.html.erb
<h1>New Presence</h1>

<%= render 'form', presence: @presence %>

<%= link_to 'Back', presences_path %>

app/views/presences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Situation:</strong>
  <%= @presence.situation %>
</p>

<p>
  <strong>Student:</strong>
  <%= @presence.student_id %>
</p>

<p>
  <strong>Lesson:</strong>
  <%= @presence.lesson_id %>
</p>

<%= link_to 'Edit', edit_presence_path(@presence) %> |
<%= link_to 'Back', presences_path %>