config/routes.rb
Rails.application.routes.draw do
  resources :presences
  resources :students
  resources :lessons
  resources :teachers
  resources :professors
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :teacher
  has_many :students
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:code, :teacher_id)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, local: true) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :teacher_id %>
    <%= form.text_field :teacher_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lessons</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.code %></td>
        <td><%= lesson.teacher_id %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @lesson.code %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @lesson.teacher_id %>
</p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>